-- Active: 1751393237310@@127.0.0.1@5432@cinevodb
INSERT INTO genres (name) VALUES
('Action'),
('Adventure'),
('Animation'),
('Comedy'),
('Crime'),
('Documentary'),
('Drama'),
('Family'),
('Fantasy'),
('History'),
('Horror'),
('Music'),
('Mystery'),
('Romance'),
('Science Fiction'),
('TV Movie'),
('Thriller'),
('War'),
('Western');

INSERT INTO directors (name) VALUES
('Christopher Nolan'),
('Steven Spielberg'),
('Quentin Tarantino'),
('Martin Scorsese'),
('James Cameron'),
('Ridley Scott'),
('Alfred Hitchcock'),
('George Lucas'),
('Francis Ford Coppola'),
('Woody Allen');

INSERT INTO casts (name) VALUES
('Leonardo DiCaprio'),
('Joseph Gordon-Levitt'),
('Ellen Page'),
('Christian Bale'),
('Heath Ledger'),
('Aaron Eckhart'),
('Sam Neill'),
('Laura Dern'),
('Jeff Goldblum'),
('Liam Neeson'),
('Ben Kingsley'),
('Ralph Fiennes'),
('John Travolta'),
('Uma Thurman'),
('Samuel L. Jackson'),
('Brad Pitt'),
('Christoph Waltz'),
('Mélanie Laurent'),
('Jonah Hill'),
('Margot Robbie'),
('Kate Winslet'),
('Sam Worthington'),
('Zoe Saldana'),
('Sigourney Weaver'),
('Russell Crowe'),
('Joaquin Phoenix'),
('Connie Nielsen'),
('Tom Skerritt'),
('John Hurt'),
('Anthony Perkins'),
('Janet Leigh'),
('Vera Miles'),
('James Stewart'),
('Grace Kelly'),
('Thelma Ritter'),
('Mark Hamill'),
('Harrison Ford'),
('Carrie Fisher'),
('Ewan McGregor'),
('Natalie Portman'),
('Liam Neeson'),
('Marlon Brando'),
('Al Pacino'),
('James Caan'),
('Martin Sheen'),
('Robert Duvall'),
('Woody Allen'),
('Diane Keaton'),
('Owen Wilson'),
('Rachel McAdams'),
('Marion Cotillard');

SELECT u.id, p.fullname, u.email, u.password, p.phone FROM users u 
JOIN profiles p ON u.profile_id = p.id 
WHERE u.id = 2 AND roles = 'user';

INSERT INTO payment_method (name)
VALUES ('dana'),
('google pay'),
('bca'),
('ovo'),
('paypal'),
('gopay'),
('visa'),
('bri');