services:
  cinevo:
    image: ghcr.io/vsalcode/fgo24-react-cinevo:latest
    ports:
      - 9402:80
  app:
     image: ghcr.io/vsalcode/fgo24-be-tickitz:latest
     ports:
      - 9403:8080
     networks:
      - netapp
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
    volumes:
      - data_postgres:/var/lib/postgresql/data
    networks:
      - netapp
  redis:
    image: redis
    volumes:
      - data_redis:/data
    networks:
      - netapp
volumes:
  data_postgres:
  data_redis:
networks:
  netapp: