name: Build & Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/vsalcode/fgo24-be-tickitz:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/vsalcode/fgo24-be-tickitz:latest

  deploy:
    name: Deploy & Migrate
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Deployment Files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: faisal
          port: 9401
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "migrations,docker-compose.yml"  
          target: "/home/faisal/deploy"

      - name: SSH Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: faisal
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 9401
          script: |
            cd /home/faisal/deploy
            
            docker stop $(docker ps -q --filter publish=9402) 2>/dev/null || true
            docker stop $(docker ps -q --filter publish=9403) 2>/dev/null || true
            
            docker compose down --remove-orphans
            docker network rm deploy_netapp 2>/dev/null || true
            
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker compose pull
            
            docker network create --label com.docker.compose.network=netapp --label com.docker.compose.project=deploy deploy_netapp || true
            
            docker volume rm deploy_data_postgres 2>/dev/null || true
            
            docker compose up -d db redis
            
            echo "Waiting for database to be ready..."
            for i in {1..60}; do  # Increased timeout
              container_state=$(docker compose ps -q db | xargs docker inspect -f '{{.State.Status}}' 2>/dev/null)
              if [ "$container_state" = "running" ]; then
                if docker compose exec -T db pg_isready -U postgres; then
                  echo "Database is ready!"
                  break
                fi
              fi
              echo "Waiting for database... ($i/60)"
              sleep 2
            done
            
            docker run --rm \
              --network deploy_netapp \
              -v "/home/faisal/deploy/migrations:/migrations" \
              migrate/migrate \
              -path=/migrations \
              -database "postgres://postgres:1@db:5432/cinevodb?sslmode=disable" \
              up
            
            docker compose up -d
            
            echo "Deployment verification:"
            docker compose ps
            curl -I http://localhost:9403 || true